### ISSUE TITLE
Title conflicts with axis labels

### ISSUE THREAD

**Issue by avonow** [titanclass/yew-chart#18]
In its current position, the title conflicts with the axis labels. Since the title is currently already rotated, if the user attempts to provide a new transformation to change the title position, the rotation will be overridden. 

From line 127 in `vertical_axis.rs`:
`transform={format!("rotate({}, {}, {})", rotation, x, y)}`

![image](https://user-images.githubusercontent.com/53909014/157388131-43fc5aff-3c62-434b-80b3-6b14fb79db8c.png)

**Comment by huntc** [comment]
Work performed a couple of months ago should now provide complete control over CSS positioning.
