### ISSUE TITLE
Example scatter plot and horizontal scale step

### ISSUE THREAD

**Issue by avonow** [titanclass/yew-chart#30]
In the example scatter plot, the `horizontal_scale_step` doesn't change as expected.

For example, when changing the value in the example from 2 to 1000000, the graph stays the same.

**Comment by huntc** [comment]
The horizontal scale step is used to determine when there is a gap in data, such that if a line chart was drawn, then if two data items are separated by more than this can, the line will end and start again. For scatter plots, this property does not get used. I shall document it.
