### ISSUE TITLE
Yew 0.20

### ISSUE THREAD

**Issue by Timmmm** [titanclass/yew-chart#47]
I might be doing something wrong but I tried one of the examples with Yew 0.20 and get this error:

```
error[E0277]: the trait bound `Series<i64, f32>: yew::Component` is not satisfied
  --> src\chart.rs:52:14
   |
52 |             <Series<i64, f32>
   |              ^^^^^^ the trait `yew::Component` is not implemented for `Series<i64, f32>`
   |
   = help: the trait `yew::Component` is implemented for `ContextProvider<T>`
   = note: required for `Series<i64, f32>` to implement `yew::BaseComponent`
   = note: this error originates in the macro `html` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Any idea what has changed?

**Comment by Timmmm** [comment]
Ah never mind I guess it's because Yew 0.20 is a breaking change. Yew-chart explicitly depends on 0.19.

Anyway if I change it to depend on 0.20 and fix a couple of `changed` methods as described [here](https://yew.rs/docs/next/migration-guides/yew/from-0_19_0-to-0_20_0#changed-method-on-components) then it seems to work!

**Comment by huntc** [comment]
Thanks for the issue! I’ve not got round to updating to 0.20 for some of our production stuff. Probably should re-evaluate that, or at least keep a 0.19 branch going.

**Comment by huntc** [comment]
Going to close this out as we have #49
